databases:
  - name: Sushisearch_DB
    databaseName: sushisearch_db
    user: Sushisearch
    region: singapore

services:
  - type: web
    name: Sushisearch
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Sushisearch_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

